### ISSUE TITLE
Incorrect binary value in 2 diagrams

### ISSUE THREAD

**Issue by TheSavage** [sethmlarson/diagrams#1]
The binary/ascii/utf-8 value of 'a' (hex 0x61) is not 01010111, but rather 01100001.
This is used incorrectly in both the Giant reference card, and in the "ascii encoding" diagram above it.

This seems to have been pointed out before, because the Hex and UTF-8 values in the diagrams on github have been updated to match the binary -> U+57 or 0x57.  However, that is correcting the wrong thing, as 'a' should be 0x61.  The binary should be corrected to 01100001, and the U+57 and 0x57 values put back to  U+61 and 0x61.

Don't get me wrong this is an awesome resource, and really helped me to finally understand UTF-8

**Comment by sethmlarson** [comment]
Thanks for reporting this, yeah I've fixed it on the article but hasn't found time yet to fix it here. :)

Glad they helped you learn!

**Comment by TheSavage** [comment]
Happy to!  FYI - the article is still incorrect, but if you change the binary from 01010111 to 01100001 it will be correct.

**Comment by sethmlarson** [comment]
@TheSavage Done!

**Comment by TheSavage** [comment]
@sethmlarson Excellent!
